### ISSUE TITLE
Finishing off tracks with separate ID's

### ISSUE THREAD

**Issue by aseams** [Foohy/gm-rollercoaster#17]
I have used your addon for about a month now and it's amazing. So, about a week ago I started building a track and decided to finally try putting in a trackless bit. As soon as I was about to bring the track back and connect it to the original orb, I realised that being on different ID's, it wouldn't work. I tried everything I could but it still wouldn't work. Theres no error or anything that I can see, so that's not too helpful. If any other information is needed just ask.

**Comment by Foohy** [comment]
Yeah, having trackless transitions is actually a bit of a hack, since it sees them as two completely separated rollercoasters. Currently to bring it back to the main track, you'd have to have another trackless section.

There's a lot of things I'd like to implement, but they would be large enough changes that I'd rather recode the addon from scratch (changing the splining algorithm from catmull-rom to bezier is a big one). Unfortunately, I've had a lot less time to work on rollercoaster, so I'm not sure if I'd be able to do that any time soon.
